export const images = {
  'Aloo Matar': '/veg/Aloo-Matar.jpg',
  'Bendi Masala': '/veg/bendi-masala.jpg',
  'Butter Naan': '/veg/Butter-Naan.jpg',
  'chilliBabyCorn Recipe': '/veg/chilliBabyCorn.jpeg',
  'Dal Makhani': '/veg/dal-makhani.jpeg',
  'Garlic Mushroom': '/veg/garlic-mushroom.jpg',
  'Gobi Fried Rice': '/veg/gobi-fried-rice.jpg',
  'Jeera Rice': '/veg/Jeera-Rice.jpg',
  'Kadai Mushroom': '/veg/kadai-mushroom.jpg',
  'Kaju Paneer': '/veg/kaju-paneer.jpg',
  'Kheer': '/veg/kheer.jpeg', 
  'lemon Rice': '/veg/lemon-rice.jpg',
  'Mixed Vegetable Curry': '/veg/mixed-vegetable-curry.jpg',
  'Paneer Biryani': '/veg/paneer-biryani.jpg',
  'Paneer Fry': '/veg/paneerfry.jpg',
  'Pav Bhaji': '/veg/Pav_bhaji.jpg',
  'Traditional Sambar': '/veg/Sambar.jpg',
  'Schezwan Fried Rice': '/veg/SchezwanFriedRice.jpg',
  'Stuffed Brinjal':'/veg/stuffed-brinjal.jpg',
  'Tandoori Paneer':'/veg/tandoori-paneer.jpeg',
  'Tomato Rice': '/veg/tomatorice.jpg',
  'Veg Biryani': '/veg/veg-biryani.jpg',
  'Veg manchurian':'/veg/veg-manchurian.jpeg',
  'Veg Noodles':'/veg/vegetable-noodles.jpg',
  'Vegetable Pulao':'/veg/Vegetable-Pulao.jpg',
  'South Indian Egg Curry' :'/nonveg/eggcurry.jpg',
  'Egg Fried Rice':'/nonveg/eggrice.jpg',
  'Egg Bhurji':'/nonveg/bhurji.jpg',
  'Apollo Fish Recipe':'/nonveg/apollo.jpg',
  'Grilled Chicken Sandwich':'/nonveg/grilled.jpeg',
  'Dry Chicken Ghee Roast':'/nonveg/gheeroast.jpeg',
  'Andhra Gongura Chicken':'/nonveg/gongura.jpg',
  'Chicken Spaghetti Pasta':'/nonveg/spaghetti.jpg',
  'Chicken Nuggets':'/nonveg/nuggets.jpeg',
  'Schezwan Chicken':'/nonveg/SchezwanChicken3.jpg',
  'Chicken Majestic':'/nonveg/chickenMajestic.jpeg',
  'Chicken Manchuria':'/nonveg/ChickenManchuria.jpg',
  'Chicken Lollipop':'/nonveg/chicken-lollipop.jpg',
  'Chicken Butter Masala':'/nonveg/chicken-butter-masala.jpg',
  'Thalassery Biryani':'/nonveg/ThalasseriChickenBiryani.jpg',
  'Chicken Chettinad':'/nonveg/chickenchettinad.jpg',
  'Chicken 65 Recipe':'/nonveg/chicken65.jpg',
  'Chicken Tikka':'/nonveg/chickentikka.jpeg',
  'Shami Kebab':'/nonveg/shami kebab.jpg',
  'Hyderabadi Biryani':'/nonveg/hyd-biryani.jpg',
  'Chicken White Sauce Pasta':'nonveg/chickenwhitesauce.jpg',
  'Chicken Alfredo Pasta':'/nonveg/Chicken-Alfredo.jpg',
  'Prawns Curry':'/nonveg/prawncurry.jpg',
  'Fish Fry':'/nonveg/fishfryy.jpeg',
  'Mutton Biryani':'/nonveg/Mutton-Biryani.jpg',
  'Chicken Biryani':'/nonveg/chicken-biryani.jpg',
  'Butter Chicken':'/nonveg/butterchicken.jpg',
  'Tandoori Chicken':'/nonveg/tandoori.jpg'
  };